image: php:8.2-cli-alpine

definitions:
  steps:
    # Digital Ocean Droplet Environment - Step 1
    - step: &composer
        name: Composer
        script:
          - php -r "readfile('https://getcomposer.org/installer');" | php -- --install-dir=/usr/local/bin --filename=composer --version=2.5.8
          - composer install --no-dev -d $BITBUCKET_CLONE_DIR/code
        artifacts:
          - code/vendor/**
          - code/web/wp/**
          - code/web/app/plugins/**
          - code/web/app/mu-plugins/**
        caches:
          - composer

    # Lightsail Environment - Step 2
    - step: &webpack
        name: Webpack
        image: node:18-slim
        script:
          - apt-get update
          - apt-get install -y git libnotify-bin
          - cd code/web/app/themes/murr
          - npm install
          - npm run build
        artifacts:
          - code/vendor/**
          - code/web/wp/**
          - code/web/app/plugins/**
          - code/web/app/mu-plugins/**
          - code/web/app/themes/murr/public/**
        caches:
          - node

    # Droplet Environment - Step 3
    - step: &droplet-deploy
        image: atlassian/default-image:2
        script:
          - find code -type d -exec chmod 755 {} \;
          - find code -type f -exec chmod 644 {} \;
          - pipe: atlassian/rsync-deploy:0.4.4
            variables:
              USER: $USER
              SERVER: $SERVER
              REMOTE_PATH: $DEPLOY_ROOT
              LOCAL_PATH: 'code/*'
              EXTRA_ARGS: '--exclude=web/app/uploads'

pipelines:
  branches:
    master:
      - step: *composer
      - step: *webpack
      - step:
          name: Deploy to Staging
          deployment: staging
          <<: *droplet-deploy
  tags:
    release/*:
      - step: *composer
      - step: *webpack
      - step:
          name: Deploy to Production
          deployment: production
          <<: *droplet-deploy
