services:
  composer:
    extends:
      file: ./docker/services-common.yml
      service: wordpress
    build:
      target: base
    entrypoint: ["composer"]
    volumes:
      - ./code:/app
    networks:
      - default
      - traefik
  wp:
    image: wordpress:cli-2.10.0-php${PHP_VERSION:-8.3}
    extends:
      file: ./docker/services-common.yml
      service: code-base
    entrypoint: ["wp"]
    networks:
      - default
      - traefik
  npm:
    extends:
      file: ./docker/services-common.yml
      service: wordpress
    build:
      target: theme-base
    entrypoint: ["npm"]
    volumes:
      - ./code/web/app/themes/io:/theme
    networks:
      - default
      - traefik
  wordmove:
    extends:
      file: ./docker/services-common.yml
      service: wordmove
    networks:
      - default
      - traefik

networks:
  traefik:
    name: traefik-network
    external: true

