# See: https://www.nginx.com/resources/wiki/start/topics/recipes/wordpress/

server {
    listen 80;
    server_name {{NGINX_SERVER_NAME}};
    root {{NGINX_ROOT}};
    index index.php;

    client_max_body_size 8G;

    include /var/www/html/config/*.conf;

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_intercept_errors on;
        fastcgi_pass {{FPM_HOST}}:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }
}
