# An example of a Staging environment with:
# 1. Caching enabled
# 2. An external database
# 3. Persistent user uploads
# 4. Ingress with TLS
environment: staging
hostName: &commonName murr.mirandaknee.site
deploymentAnnotations:
  downscaler/exclude: "true"

varnish:
  enabled: true
  service:
    type: ClusterIP
  purgeWhitelist:
    - "127.0.0.1"
    - "localhost"
    - "192.168.0.0/16"

redis:
  enabled: true

mariadb:
  enabled: false
  # host: gh-shared-cluster.ccy5divwl57m.us-east-1.rds.amazonaws.com
  auth:
    database: murr_com_staging
    username: murr
    # password: <secret>

uploadsPVC:
  enabled: true
  annotations:
    helm.sh/resource-policy: keep
  accessModes:
    - ReadWriteMany
  storageClass: fs-0cdf42b8-efs-sc

service:
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: *commonName
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: "{{ .Release.Name }}-http"
                port:
                  name: varnish
  tls:
    - secretName: "{{ .Release.Name }}-tls"
      hosts:
        - *commonName
