entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "murr-network"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
